# Generated by Django 3.1.7 on 2021-03-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210303_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contect',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='contect',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
    ]
